- name: AnsibleDocker integration
  hosts: webserver
  become: true
  become_user: root
  vars:
   repo_name: https://github.com/Sonal0409/AnsibleDockerdemo.git
   image_name: myansible02
  tasks:
  - name: Install multiple packages on host server
    package: name={{item}}    state=present
    loop:
     - git
     - docker
     - tree
  - name: Start docker service
    service: name=docker state=started
  - name: Clone a git repo
    git:
     repo={{repo_name}}
     dest=/tmp/myrepo
  - name: Build dockerfile into an Image
    command: chdir=/tmp/myrepo docker build -t {{image_name}} .
  - name: Run the image to deploy container
    command: docker run -d -P {{image_name}}
